name: ❓ Question
description: Ask a question about the project.
title: "❓ "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know? Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional context, code snippets, or screenshots that might help clarify your question.
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is your question?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the project are you using? (e.g., 1.0.0)
    validations:
      required: false